export const FETCH_ALL = "FETCH_ALL";

export const FILTER_SUBJECT_RATING = "FILTER_SUBJECT_RATING";
export const FETCH_ALL_INSTRUCTOR_COURSES = "FETCH_ALL_INSTRUCTOR_COURSES";
export const FILTER_INSTRUCTOR_COURSES = "FILTER_INSTRUCTOR_COURSES";

export const FILTER_COURSES = "FILTER_COURSES";

export const CREATE_COURSE = "CREAE_COURSE";

export const GET_COURSE = "GET_COURSE";
