export const FETCH_CURRENCY_RATES = "FETCH_CURRENCY_RATES";
export const GET_SELECTED_COUNTRY = "GET_SELECTED_COUNTRY";
export const CHANGE_SELECTED_COUNTRY = "CHANGE_SELECTED_COUNTRY";
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";