export const FETCH_CURRENCY_RATES = "FETCH_CURRENCY_RATES";
export const GET_SELECTED_COUNTRY = "GET_SELECTED_COUNTRY";
export const CHANGE_SELECTED_COUNTRY = "CHANGE_SELECTED_COUNTRY";
export const START_LOADING_CURRENCY = "START_LOADING_CURRENCY";
export const END_LOADING_CURRENCY = "END_LOADING_CURRENCY";
