export const FETCH_INSTRUCTOR = "FETCH_INSTRUCTOR";
export const FETCH_INSTRUCTORS = "FETCH_INSTRUCTORS";
export const ADD_INSTRUCTOR = "ADD_INSTRUCTOR";
export const FILTER_INSTRUCTOR_COURSES = "FILTER_INSTRUCTOR_COURSES";
export const ADD_INSTRUCTOR_RATING = "ADD_INSTRUCTOR_RATING";
export const ADD_INSTRUCTOR_REVIEW = "ADD_INSTRUCTOR_REVIEW";
