export const REPORT_PROBLEM = "REPORT_PROBLEM";
export const START_LOADING_PROBLEMS = "START_LOADING_PROBLEMS";
export const END_LOADING_PROBLEMS = "END_LOADING_PROBLEMS";
export const GET_REPORTED_PROBLEMS = "GET_REPORTED_PROBLEMS";
export const UPDATE_REPORTED_PROBLEM = "UPDATE_REPORTED_PROBLEM";
